### ISSUE TITLE
setBias() and getBias() from code

### ISSUE THREAD

**Issue by manuelbonilla** [CentroEPiaggio/ATI_FTSensors#1]
It would be usefult to have two functions like

```
bool getBias(float*)
bool setBias()
```

to allow resetting and reading the bias set on the sensor from code. This last part would in general be useful for safety reasons.

**Comment by ciottisimone88** [comment]
With the commit 3f32d4e1323543c9b931a3784f3c003ab3018260 they were added the functions

- `void getBias(T& f, U& t)`, where `T` and `U` can be `std::vector<double>`, `Eigen::VectorXd`, and `Eigen::Vector3d`

- `void getBias(double& fx, double& fy, double& fz, double& tx, double& ty, double& tz)`

- `bool calibration(unsigned int samples_number = 0)`, if `samples_number` is zero then the samples number is equal to the sensor data rate
